services:
  bot:
    container_name: 1cmbot_bot
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot/src:/app/bot/src

  prisma:
    container_name: 1cmbot_prisma
    build:
      context: .
      dockerfile: prisma/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Singapore
      POSTGRES_HOST: database
    ports:
      - 5555:5555
    volumes:
      - ./prisma:/app/prisma
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: 1cmbot_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3
    image: docker.io/library/postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      TZ: Asia/Singapore
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
