services:
  bot:
    container_name: 1cmbot_bot
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot/src:/app/bot/src

  prisma:
    container_name: 1cmbot_prisma
    build:
      context: .
      dockerfile: prisma/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Singapore
      POSTGRES_HOST: database
    ports:
      - 5555:5555
    volumes:
      - ./prisma:/app/prisma
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
    image: mysql:9.0.1
    restart: always
    ports:
      - 3306:3306
    expose:
      - '3306'
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
